### ISSUE TITLE
Fix maintenance script issues with production data. 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/formulasearch#3]
**Issue description**:
Formulasearch index-updating works in production with severe adaptions. 
- Maintenance scripts adress just one page 'MathSearchTest' 
- Severe fixes in creation of revision id (just use a forward counter as id)

These problems are related to the creation of revisionId. 
Workaround for production is currently on branch. 

It is difficult to debug these issues on running production machine, therefore restore data locally and reproduce the issues to fix them. 

**TODOS**: 

- [ ] get all data from production env (backups)
- [ ] restore backups to  local db  
- [ ] identify issue with local IDE etc.
- [ ] fix issue.  

**Acceptance-Criteria** 
- Maintenance scripts can create indices for wikipages. 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by Hyper-Node** [comment]
This can most probably be skipped since maintenance scripts won't be used in final implementation, see here instead API :
MaRDI4NFDI/portal-compose#193
