### ISSUE TITLE
Check evaluation for ARQMATH formula retrieval 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/formulasearch#4]
**Issue description**:
"
 Dear ARQMath community,

For the information retrieval course project here at RIT (Rochester Institute of Technology), we have developed PyTerrier-based code which is publicly available here: [https://gitlab.com/dprl/pt-arqmath](https://deref-gmx.net/mail/client/EsTzqNfqye8/dereferrer/?redirectUrl=https%3A%2F%2Fgitlab.com%2Fdprl%2Fpt-arqmath)
The effectiveness measures for the TF-IDF model are slightly better. We are also tokenizing formulas differently than in ARQMath-2 for the formulas in the pt-arqmath code base.

We would like to thank Craig and Nicola for providing Pyterrier with comprehensive documentation online. The related paper is cited on the GitLab repo.

Best wishes,
ARQMath Organizers
(Behrooz, Vit, Anurag, Doug, and Richard)
 "
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
