### ISSUE TITLE
Formulasearch API Access

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/formulasearch#5]
**Issue description**:
 Instead of running on existing BaseX harvest-files and maintance scripts. Formulasearch should upgrade index with API Requests to BaseX REST API Endpoint.  
 
**TODOS**: 
- [ ] Define Hooks which trigger formula update 
- [ ] Write data forwarding to BaseX Endpoint
- [ ] Check if persistant storage is possible (since no filebase) 

**Acceptance-Criteria** 
- Ideally working formulasearch in portal 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
